# Generated by Django 5.1.14 on 2026-06-06 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("image", "Image guessing"),
                            ("chapter", "Chapter guessing"),
                            ("wordle", "Wordle"),
                            ("music", "Music guessing"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Contoh: Kelompok 1, Kelompok 2", max_length=50
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Centang untuk mengikutkan tim ini di ronde berjalan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MusicGuess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_title", models.CharField(max_length=255)),
                ("artist", models.CharField(blank=True, max_length=255)),
                ("audio_url", models.URLField(blank=True)),
                (
                    "quiz_mode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_guess",
                        to="Randomquiz.quizmode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageGuess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("answer", models.CharField(max_length=255)),
                (
                    "quiz_mode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_guess",
                        to="Randomquiz.quizmode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChapterGuess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_title", models.CharField(max_length=255)),
                ("verse_reference", models.CharField(max_length=64)),
                (
                    "quiz_mode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_guess",
                        to="Randomquiz.quizmode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordleQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_word", models.CharField(max_length=64)),
                ("max_attempts", models.PositiveSmallIntegerField(default=6)),
                (
                    "quiz_mode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wordle_quiz",
                        to="Randomquiz.quizmode",
                    ),
                ),
            ],
        ),
    ]
