# Generated by Django 5.1.14 on 2026-06-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Randomquiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageguess",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Contoh: /static/images/gambar1.jpg",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="musicguess",
            name="audio_url",
            field=models.CharField(
                blank=True, help_text="Contoh: /static/audio/lagu1.mp3", max_length=255
            ),
        ),
    ]
