# Generated by Django 5.1.14 on 2026-06-06 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Randomquiz", "0002_alter_imageguess_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterguess",
            name="answer",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="chapterguess",
            name="distractors",
            field=models.TextField(
                blank=True, help_text="Pilihan salah, pisahkan dengan koma."
            ),
        ),
        migrations.AddField(
            model_name="chapterguess",
            name="fun_fact",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapterguess",
            name="guess_type",
            field=models.CharField(
                choices=[("tokoh", "Tebak Tokoh"), ("kitab", "Tebak Kitab")],
                default="kitab",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="chapterguess",
            name="hint_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="chapterguess",
            name="hint_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="chapterguess",
            name="verse_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="imageguess",
            name="category",
            field=models.CharField(
                choices=[("person", "Tokoh"), ("place", "Tempat"), ("object", "Benda")],
                default="object",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="imageguess",
            name="distractors",
            field=models.TextField(
                blank=True,
                help_text="Pilihan salah, pisahkan dengan koma. Contoh: Daud, Musa, Abraham",
            ),
        ),
        migrations.AddField(
            model_name="imageguess",
            name="fun_fact",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="imageguess",
            name="hint_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="imageguess",
            name="hint_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="imageguess",
            name="hint_3",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="musicguess",
            name="distractors",
            field=models.TextField(
                blank=True, help_text="Pilihan salah, pisahkan dengan koma."
            ),
        ),
        migrations.AddField(
            model_name="musicguess",
            name="fun_fact",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="musicguess",
            name="hint_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="musicguess",
            name="hint_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="musicguess",
            name="lyrics_snippet",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="wordlequiz",
            name="category",
            field=models.CharField(
                choices=[("tokoh", "Tokoh"), ("tempat", "Tempat"), ("umum", "Umum")],
                default="umum",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="wordlequiz",
            name="fun_fact",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="wordlequiz",
            name="hint",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="wordlequiz",
            name="hint_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="chapterguess",
            name="quiz_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_guess",
                to="Randomquiz.quizmode",
            ),
        ),
        migrations.AlterField(
            model_name="chapterguess",
            name="verse_reference",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="imageguess",
            name="quiz_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_guess",
                to="Randomquiz.quizmode",
            ),
        ),
        migrations.AlterField(
            model_name="musicguess",
            name="quiz_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="music_guess",
                to="Randomquiz.quizmode",
            ),
        ),
        migrations.AlterField(
            model_name="wordlequiz",
            name="quiz_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wordle_quiz",
                to="Randomquiz.quizmode",
            ),
        ),
    ]
